/*
 * Copyright (c) 2020 Weidmueller Interface GmbH & Co. KG
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _SOC__H_
#define _SOC__H_

#ifndef _ASMLANGUAGE

#define CONFIG_ZYNQ_CPU_6X4X_FREQUENCY ((CONFIG_ZYNQ_PS_REF_FREQUENCY * CONFIG_ZYNQ_ARMPLL_MULTIPLIER) / CONFIG_ZYNQ_ARMPLL_DIVISOR0)
#define CONFIG_ZYNQ_CPU_3X2X_FREQUENCY ((CONFIG_ZYNQ_PS_REF_FREQUENCY * CONFIG_ZYNQ_ARMPLL_MULTIPLIER) / (2 * CONFIG_ZYNQ_ARMPLL_DIVISOR0))

#if   (defined CONFIG_ZYNQ_CLOCK_RATIO_6321)

#define CONFIG_ZYNQ_CPU_2X_FREQUENCY   (CONFIG_ZYNQ_CPU_6X4X_FREQUENCY / 3)
#define CONFIG_ZYNQ_CPU_1X_FREQUENCY   (CONFIG_ZYNQ_CPU_6X4X_FREQUENCY / 6)

#elif (defined CONFIG_ZYNQ_CLOCK_RATIO_4221)

#define CONFIG_ZYNQ_CPU_2X_FREQUENCY   (CONFIG_ZYNQ_CPU_6X4X_FREQUENCY / 2)
#define CONFIG_ZYNQ_CPU_1X_FREQUENCY   (CONFIG_ZYNQ_CPU_6X4X_FREQUENCY / 4)

#else

#error No valid clock generation ratio provided in Zynq-7000 SOC configuration!

#endif

#define CONFIG_ZYNQ_DDR_3X_FREQUENCY   ((CONFIG_ZYNQ_PS_REF_FREQUENCY * CONFIG_ZYNQ_DDRPLL_MULTIPLIER) / CONFIG_ZYNQ_DDRPLL_DDR3X_DIVISOR0)
#define CONFIG_ZYNQ_DDR_2X_FREQUENCY   ((CONFIG_ZYNQ_PS_REF_FREQUENCY * CONFIG_ZYNQ_DDRPLL_MULTIPLIER) / CONFIG_ZYNQ_DDRPLL_DDR2X_DIVISOR0)
#define CONFIG_ZYNQ_DDRDCI_FREQUENCY   (((CONFIG_ZYNQ_PS_REF_FREQUENCY * CONFIG_ZYNQ_DDRPLL_MULTIPLIER) / CONFIG_ZYNQ_DDRPLL_DDRDCI_DIVISOR0) / CONFIG_ZYNQ_DDRPLL_DDRDCI_DIVISOR1)

#endif /* !_ASMLANGUAGE */

#endif /* _SOC__H_ */
